CREATE FUNCTION GET_NAME_PROG
(
	@NOME_BD VARCHAR(100)
)
RETURNS VARCHAR(100)
AS
BEGIN
	DECLARE @POS INT;
	SET @POS = CHARINDEX('_', @NOME_BD);

	DECLARE @RESULT VARCHAR(100);

	IF (@POS = 0 OR @POS = LEN(@NOME_BD))
		SET @RESULT = UPPER(LEFT(@NOME_BD, 1)) + LOWER(RIGHT(@NOME_BD, LEN(@NOME_BD) - 1))
	ELSE
		SET @RESULT = UPPER(LEFT(@NOME_BD, 1)) + LOWER(SUBSTRING(@NOME_BD, 2, @POS - 2)) 
			+ dbo.GET_NAME_PROG(SUBSTRING(@NOME_BD, @POS + 1, 100))
	
	RETURN @RESULT;
END;