/* RH - COMMON TABLES */


/* RH - PERFIL TABLES */

CREATE TABLE AspNetRoles
(
    Id NVARCHAR (128) NOT NULL PRIMARY KEY CLUSTERED,
    [Name] VARCHAR (256) NOT NULL,
    DESCRICAO VARCHAR (200),
    ID_CC INTEGER NOT NULL
);
