/* RH - TABELAS AUXILIARES MODULE */

CREATE TABLE CARGO
(
    ID INTEGER NOT NULL PRIMARY KEY CLUSTERED IDENTITY,
    NOME VARCHAR (150) NOT NULL,
    COD_CARGO VARCHAR (25) NOT NULL,
    ID_CC INTEGER NOT NULL
);

CREATE TABLE CATEGORIA_VINCULO
(
	ID INTEGER NOT NULL PRIMARY KEY CLUSTERED IDENTITY,
	NOME VARCHAR (80) NOT NULL,
	COD_ORIGIN VARCHAR (25) NOT NULL,
	ID_CC INTEGER NOT NULL
);

CREATE TABLE CATEGORIA_VINCULO_GED
(
	ID INTEGER NOT NULL PRIMARY KEY CLUSTERED IDENTITY,
	NOME VARCHAR (80) NOT NULL,
	COD_GED VARCHAR (50) NOT NULL,
	ID_CC INTEGER NOT NULL
);

CREATE TABLE ESTRUT_ORG_CATEGORIA
(
	ID INTEGER NOT NULL PRIMARY KEY CLUSTERED IDENTITY,
	NOME VARCHAR (200),
	ID_CC INTEGER NOT NULL
);

CREATE TABLE ESTRUT_ORG_NODE
(
	ID INTEGER NOT NULL PRIMARY KEY CLUSTERED IDENTITY,
	NOME VARCHAR (200),
	ID_CATEGORIA INTEGER NOT NULL REFERENCES ESTRUT_ORG_CATEGORIA (ID),
	ID_PARENT INTEGER REFERENCES ESTRUT_ORG_NODE (ID),
	[LEVEL] TINYINT,
	PATH_PARENTS VARCHAR (500),
	RESPONSAVEL VARCHAR (150),
	ID_CC INTEGER NOT NULL
);

CREATE TABLE FUNCAO
(
	ID INTEGER NOT NULL PRIMARY KEY CLUSTERED IDENTITY,
	NOME VARCHAR (150) NOT NULL,
	COD_ORIGIN VARCHAR (25) NOT NULL,
	ID_CC INTEGER NOT NULL
);

CREATE TABLE MOTIVO_REJEICAO
(
    ID INTEGER NOT NULL PRIMARY KEY CLUSTERED IDENTITY,
    MOTIVO VARCHAR (100) NOT NULL,
    ID_CC INTEGER NOT NULL
);

CREATE TABLE SITUACAO_FUNCIONAL
(
	ID INTEGER NOT NULL PRIMARY KEY CLUSTERED IDENTITY,
	NOME VARCHAR (120) NOT NULL,
	COD_ORIGIN VARCHAR (25) NOT NULL,
	ID_CC INTEGER NOT NULL
);
