/* RH - ACCOUNT MODULE */

CREATE TABLE AspNetUsers
(
	Id NVARCHAR (128) NOT NULL PRIMARY KEY CLUSTERED,
	Email NVARCHAR (256),
	EmailConfirmed BIT NOT NULL,
	PasswordHash NVARCHAR (max),
	SecurityStamp NVARCHAR (max),
	PhoneNumber NVARCHAR (max),
	PhoneNumberConfirmed BIT NOT NULL,
	TwoFactorEnabled BIT NOT NULL,
	LockoutEndDateUtc DATETIME,
	LockoutEnabled BIT NOT NULL,
	AccessFailedCount INT NOT NULL,
	UserName NVARCHAR (256) NOT NULL
);

CREATE TABLE AspNetUserRoles
(
	UserId NVARCHAR (128) NOT NULL REFERENCES AspNetUsers (Id),
    RoleId NVARCHAR (128) NOT NULL REFERENCES AspNetRoles (Id),
    PRIMARY KEY CLUSTERED (UserId, RoleId)
);

CREATE TABLE PESSOA
(
    ID INTEGER NOT NULL PRIMARY KEY CLUSTERED IDENTITY,
    NOME VARCHAR (120),
    TIPO_LOGRADOURO_ENUM INTEGER,
    NUMERO VARCHAR (10),
    COMPLEMENTO VARCHAR (80),
    BAIRRO VARCHAR (50),
    LOCALIDADE VARCHAR (50),
    CIDADE VARCHAR (100),
    UF CHARACTER (2),
    CEP VARCHAR (10),
    EMAIL1 VARCHAR (120),
    EMAIL2 VARCHAR (120),
    NOME_LOGRADOURO VARCHAR (80),
    ID_CC INTEGER NOT NULL,
    CREATION_USER VARCHAR (50) NOT NULL,
    UPDATE_USER VARCHAR (50),
    CREATION_DATE SMALLDATETIME NOT NULL,
    UPDATE_DATE SMALLDATETIME,
    [VERSION] TIMESTAMP NOT NULL
);

CREATE TABLE CONTA_CONTRATO
(
    ID INTEGER NOT NULL PRIMARY KEY CLUSTERED IDENTITY,
    NOME VARCHAR (120) NOT NULL,
    DOMAIN VARCHAR (50) NOT NULL,
    STATUS_ENUM INTEGER,
    DT_INICIO DATE,
    PRAZO SMALLINT,
    DT_FINAL DATE,
    DT_ASSINATURA DATE,
    ID_PESSOA INTEGER REFERENCES PESSOA (ID),
    WA_INSTANCIA VARCHAR (50),
    WA_TOKEN VARCHAR (50),
    PROPERTIES_FILENAME VARCHAR (50),
    AWS_SES_SOURCE VARCHAR (200),
    AWS_SES_SOURCE_ARN VARCHAR (200),
    CREATION_USER VARCHAR (50) NOT NULL,
    UPDATE_USER VARCHAR (50),
    CREATION_DATE SMALLDATETIME NOT NULL,
    UPDATE_DATE SMALLDATETIME,
    [VERSION] TIMESTAMP NOT NULL
);

CREATE TABLE USUARIO
(
    ID INTEGER NOT NULL PRIMARY KEY CLUSTERED REFERENCES PESSOA (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    IdAspNetUsers NVARCHAR (128) NOT NULL REFERENCES AspNetUsers (Id),
    STATUS_ENUM INTEGER NOT NULL,
    NOTAS VARCHAR (800),
    ID_CC INTEGER NOT NULL REFERENCES CONTA_CONTRATO (ID),
    CREATION_USER VARCHAR (50) NOT NULL,
    UPDATE_USER VARCHAR (50),
    CREATION_DATE SMALLDATETIME NOT NULL,
    UPDATE_DATE SMALLDATETIME,
    [VERSION] TIMESTAMP NOT NULL
);
