/* RH - CADASTRO MODULE */

CREATE TABLE FUNCIONARIO
(
    ID INTEGER NOT NULL PRIMARY KEY CLUSTERED REFERENCES USUARIO (ID) ON UPDATE CASCADE ON DELETE CASCADE,
    CPF CHARACTER (11),
    RG VARCHAR (25),
    ORGAO_EMISSOR VARCHAR (50),
    NASCIMENTO DATE,
    SEXO_ENUM INT,
    NOME_MAE VARCHAR (120),
    NOME_PAI VARCHAR (120),
    DATA_SOLICI_APOSENTADORIA DATE,
    DATA_APOSENTADORIA DATE,
    TIPO_APOSENTADORIA VARCHAR (20),
    N_OFICIO VARCHAR (30)
);

CREATE TABLE CONTATO
(
    ID INTEGER NOT NULL PRIMARY KEY CLUSTERED IDENTITY,
	NOME VARCHAR (120) NOT NULL,
	DESCRICAO VARCHAR (150),
	TITULO VARCHAR (30),
	ID_PESSOA INTEGER NOT NULL REFERENCES PESSOA (ID),
	CREATION_USER VARCHAR (50) NOT NULL,
	UPDATE_USER VARCHAR (50),
	CREATION_DATE SMALLDATETIME NOT NULL,
	UPDATE_DATE SMALLDATETIME,
	[VERSION] TIMESTAMP NOT NULL
);

CREATE TABLE TELEFONE
(
	ID INTEGER NOT NULL PRIMARY KEY CLUSTERED REFERENCES CONTATO (ID) ON UPDATE CASCADE ON DELETE CASCADE,
	NUMERO CHARACTER (9) NOT NULL,
	DDD CHARACTER (2) NOT NULL,
	TIPO_ENUM SMALLINT NOT NULL
);

CREATE TABLE EMAIL
(
	ID INTEGER NOT NULL PRIMARY KEY CLUSTERED REFERENCES CONTATO (ID) ON UPDATE CASCADE ON DELETE CASCADE,
	ENDERECO VARCHAR (150) NOT NULL
);

CREATE TABLE REDE_SOCIAL
(
	ID INTEGER NOT NULL PRIMARY KEY CLUSTERED REFERENCES CONTATO (ID) ON UPDATE CASCADE ON DELETE CASCADE,
	TIPO_ENUM SMALLINT NOT NULL
);

CREATE TABLE VINCULO
(
    ID INTEGER NOT NULL PRIMARY KEY CLUSTERED IDENTITY,
    ID_FUNCIONARIO INTEGER NOT NULL REFERENCES FUNCIONARIO (ID),
    MATRICULA_ANTIGA VARCHAR (50),
    MATRICULA_ATUAL VARCHAR (50),
    DATA_ADMISSAO DATE,
    DATA_AFASTAMENTO DATE,
    DATA_DEMISSAO DATE,
    ID_CARGO INTEGER REFERENCES CARGO (ID),
    ID_FUNCAO INTEGER REFERENCES FUNCAO (ID),
    LOTACAO VARCHAR (50),
    ORGAO_EMPRESA VARCHAR (50),
    ID_SITUACAO_FUNCIONAL INTEGER REFERENCES SITUACAO_FUNCIONAL (ID),
    SITUACAO_GED_ENUM SMALLINT,
    ID_CATEGORIA_VINCULO INTEGER REFERENCES CATEGORIA_VINCULO (ID),
    ID_CATEGORIA_VINCULO_GED INTEGER REFERENCES CATEGORIA_VINCULO_GED (ID),
    ID_ESTRUT_ORG_NODE INTEGER REFERENCES ESTRUT_ORG_NODE (ID),
    ID_CC INTEGER NOT NULL,
    CREATION_USER VARCHAR (50) NOT NULL,
    UPDATE_USER VARCHAR (50),
    CREATION_DATE SMALLDATETIME NOT NULL,
    UPDATE_DATE SMALLDATETIME,
    [VERSION] TIMESTAMP NOT NULL
);
