/* RH - ACERVO MODULE */

CREATE TABLE ARMAZEM
(
    ID INTEGER NOT NULL PRIMARY KEY CLUSTERED IDENTITY,
    ENDERECO VARCHAR (150) NOT NULL,
    ID_CC INTEGER NOT NULL
);

CREATE TABLE PASTA_DOC
(
    ID INTEGER NOT NULL PRIMARY KEY CLUSTERED IDENTITY,
    ID_VINCULO INTEGER NOT NULL REFERENCES VINCULO (ID),
    PASTA_FISICA VARCHAR (50),
    QTD_DOC INTEGER,
    DATA_ARQUIVAMENTO DATE,
    ID_ARMAZEM INTEGER REFERENCES ARMAZEM (ID),
    NUMERO_ARQUIVO VARCHAR (50),
    NUMERO_GAVETA VARCHAR (50),
    NUMERO_PASTA VARCHAR (50),
    ID_CC INTEGER NOT NULL,
    CREATION_USER VARCHAR (50) NOT NULL,
    UPDATE_USER VARCHAR (50),
    CREATION_DATE SMALLDATETIME NOT NULL,
    UPDATE_DATE SMALLDATETIME,
    [VERSION] TIMESTAMP NOT NULL
);

CREATE TABLE IMG_ANEXO
(
    ID_PASTA_DOC INTEGER NOT NULL REFERENCES PASTA_DOC (ID),
    PAGINA INTEGER NOT NULL IDENTITY,
    S3_BUCKET VARCHAR (150),
    S3_KEY VARCHAR (150),
    CREATION_USER VARCHAR (50) NOT NULL,
    UPDATE_USER VARCHAR (50),
    CREATION_DATE SMALLDATETIME NOT NULL,
    UPDATE_DATE SMALLDATETIME,
    [VERSION] TIMESTAMP NOT NULL,
    PRIMARY KEY CLUSTERED (ID_PASTA_DOC, PAGINA) 
);

CREATE TABLE IMG_ANEXO_VERSO
(
    ID_PASTA_DOC INTEGER NOT NULL,
    PAGINA INTEGER NOT NULL,
    PRIMARY KEY CLUSTERED (ID_PASTA_DOC, PAGINA),
	FOREIGN KEY (ID_PASTA_DOC, PAGINA) REFERENCES IMG_ANEXO (ID_PASTA_DOC, PAGINA) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE CATALOGACAO
(
    ID INTEGER NOT NULL PRIMARY KEY CLUSTERED IDENTITY,
    ID_PASTA_DOC INTEGER NOT NULL,
    PAGINA INTEGER NOT NULL,
    TAG_TITULO VARCHAR (200) NOT NULL,
    TAG_SUBTITULO VARCHAR (200),
	FOREIGN KEY (ID_PASTA_DOC, PAGINA) REFERENCES IMG_ANEXO (ID_PASTA_DOC, PAGINA)
);

CREATE TABLE PASTA_IR
(
    ID INTEGER NOT NULL PRIMARY KEY CLUSTERED IDENTITY,
    ID_FUNCIONARIO INTEGER NOT NULL REFERENCES FUNCIONARIO (ID),
    ANO_DECLARACAO SMALLINT NOT NULL,
    FLAG_ISENTO BIT NOT NULL,
    QTD_DOC INTEGER NOT NULL,
    ID_CC INTEGER NOT NULL,
    DH_CRIACAO SMALLDATETIME NOT NULL,
    DH_ALTERACAO SMALLDATETIME,
    USER_INC VARCHAR (25) NOT NULL,
    USER_ALT VARCHAR (25),
	[VERSION] TIMESTAMP NOT NULL,
    UNIQUE (ID_FUNCIONARIO, ANO_DECLARACAO)
);

CREATE TABLE IMG_ANEXO_IR
(
    ID_PASTA_IR INTEGER NOT NULL REFERENCES PASTA_IR (ID),
    PAGINA INTEGER NOT NULL IDENTITY,
    S3_BUCKET VARCHAR (256),
    S3_KEY VARCHAR (256),
	TITULO VARCHAR (120),
	IDENTIFICACAO VARCHAR (120),
	FILE_EXTENSION VARCHAR (5),
    USER_UPLOAD VARCHAR (50) NOT NULL,
    DH_UPLOAD SMALLDATETIME NOT NULL,
    STATUS_ENUM INTEGER NOT NULL,
    TIPO_ANEXO_ENUM INTEGER,
    ID_MOTIVO_REJEICAO INTEGER REFERENCES MOTIVO_REJEICAO (ID),
    ID_APROVADO_POR INTEGER REFERENCES USUARIO (ID),
    FLAG_APROV BIT,
    DATA_APROV SMALLDATETIME,
    PRIMARY KEY CLUSTERED (ID_PASTA_IR, PAGINA)
);

CREATE TABLE IMG_ANEXO_IR_VERSO
(
    ID_PASTA_IR INTEGER NOT NULL, 
    PAGINA INTEGER NOT NULL,
    PRIMARY KEY CLUSTERED (ID_PASTA_IR, PAGINA),
    FOREIGN KEY (ID_PASTA_IR, PAGINA) REFERENCES IMG_ANEXO_IR (ID_PASTA_IR, PAGINA) ON UPDATE CASCADE ON DELETE CASCADE
);
