/* RH - PERFIL MODULE */

CREATE TABLE CASO_USO
(
    ID INTEGER NOT NULL PRIMARY KEY CLUSTERED IDENTITY,
    NOME VARCHAR (100)  NOT NULL,
    DESCRICAO VARCHAR (800)
);

CREATE TABLE MODELO_AUTORIZACAO
(
    ID_CASO_USO INTEGER NOT NULL REFERENCES CASO_USO (ID),
    TRANSACAO VARCHAR (30) NOT NULL,
    ADM BIT NOT NULL,
    EXT BIT NOT NULL,
    [INT] BIT NOT NULL,
    DESCRICAO VARCHAR (200),
    PRIMARY KEY CLUSTERED (ID_CASO_USO, TRANSACAO)
);

CREATE TABLE AspNetRolesAdm
(
    Id NVARCHAR (128) NOT NULL PRIMARY KEY CLUSTERED REFERENCES AspNetRoles (Id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE AspNetRolesExt
(
    Id NVARCHAR (128) NOT NULL PRIMARY KEY CLUSTERED REFERENCES AspNetRoles (Id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE AspNetRolesInt
(
    Id NVARCHAR (128) NOT NULL PRIMARY KEY CLUSTERED REFERENCES AspNetRoles (Id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE AUTORIZACAO
(
    ID_CASO_USO INTEGER NOT NULL,
    TRANSACAO VARCHAR (30) NOT NULL,
    ID_ASPNET_ROLES NVARCHAR (128) NOT NULL REFERENCES AspNetRoles (Id),
    AUTORIZADO BIT NOT NULL,
    PRIMARY KEY CLUSTERED (ID_CASO_USO, TRANSACAO, ID_ASPNET_ROLES),
    FOREIGN KEY (ID_CASO_USO, TRANSACAO) REFERENCES MODELO_AUTORIZACAO (ID_CASO_USO, TRANSACAO)
);
